classdef ADCP_Type
    enumeration
        Unknown
        Sentinel
        SentinelV
        Mariner
        Monitor
        MonitorV
        RioGrande
        RiverRay
        StreamPro
        QuarterMaster1500
        QuarterMaster3000
        QuarterMaster6000
        QuarterMaster1500ModBeams
        LongRanger1500
        LongRanger3000
    end
end