classdef DBTMessage < nmea.Message
% depth below transducer message
    methods
        function obj = DBTMessage()
            obj.name = 'DBT';
            obj.msg_id_pattern = obj.name;
            cp = nmea.Field.common_patterns;
            obj.fields = [...
                nmea.Field('depth_feet', "%f32", cp.float),...
                nmea.SkipField("f"),...
                nmea.Field('depth_meter', "%f32", cp.float),...
                nmea.SkipField("M"),...
                nmea.Field('depth_fathoms', "%f32", cp.float),...
                nmea.SkipField("F")];
        end
    end
end