classdef AnppPacketId < uint8
    enumeration
        % System packets
        Acknowledge(0)
        Request (1)
        BootMode (2)
        DeviceInformation (3)
        RestoreFactorySettings (4)
        Reset (5)
        SerialPortPassThrough (10)
        IPConfiguration (11)
        ExtendedDeviceInformation (13)
        SubcomponentInformation (14)

        % State packets
        SystemState (20)
        UnixTime (21)
        FormattedTime (22)
        Status (23)
        PositionStandardDeviation (24)
        VelocityStandardDeviation (25)
        EulerOrientationStandardDeviation (26)
        QuaternionOrientationStandardDeviation (27)
        RawSensors (28)
        RawGNSS (29)
        Satellites (30)
        DetailedSatellites (31)
        GeodeticPosition (32)
        ECEFPosition (33)
        UTMPosition (34)
        NEDVelocity (35)
        BodyVelocity (36)
        Acceleration (37)
        BodeAcceleration (38)
        EulerOrientation (39)
        QuaternionOrientation (40)
        DCMOrientation (41)
        AngularVelocity (42)
        AngularAcceleration (43)
        ExternalPositionAndVelocity (44)
        ExternalPosition (45)
        ExternalVelocity (46)
        ExternalBodyVelocity (47)
        ExternalHeadingVelocity (48)
        RunningTime (49)
        LocalMagneticField (50)
        OdometerState (51)
        ExternalTime (52)
        ExternalDepth (53)
        GeoidHeight (54)
        RTCMCorrections (55)
        Wind (57)
        Heave (58)
        RawSatelliteData (60)
        RawSatelliteEphemeris (61)
        ExternalOdometer (67)
        ExternalAirData (68)
        GNSSReceiverInformation (69)
        RawDVLData (70)
        GimbalState (72)
        Automotive (73)
        ExternalMagnetometer (75)
        ZeroAngularVelocity (83)
        EntendedSatellites (84)
        SensorTemperature (85)


        % configuration packets
        PacketTimerPeriod (180)
        PacketsPeriod (181)
        BaudRates (182)
        SensorRanges (184)
        InstallAlignment (185)
        FilterOptions (186)
        AdvancedFilterParameters (187)
        PortFunctionConfiguration (188)
        MagneticCalibrationValues (189)
        MagneticCalibrationConfiguration (190)
        MagneticCalibrationStatus (191)
        OdometerConfiguration (192)
        SetZeroOrientationAlignment (193)
        ReferencePointOffsets (194)
        GPIOOutputConfiguration (195)
        DualAntennaConfiguration (196)
        GNSSConfiguration (197)
        UserData (198)
        GPIOInputConfiguration (199)
        IPDataPortsConfiguration (202)
        CANConfiguration (203)

        % nodata
        NoData (255)
    end
end