classdef InstrumentMatrixProvider < InstrumentMatrixProvider
    methods(Access = protected)
        function val = get_beam_orientation_matrix(obj, adcp)
            val = obj.get_i2b_matrix(adcp);
            val = cat(4, val(:,:,:,1:2),...
                    cat(3,...
                    val(:,:,1,3), ...
                    val(:,:,2,4), ...
                    val(:,:,3,3), ...
                    val(:,:,4,4)));
        end 
    end
end