classdef InstrumentMatrixProvider < InstrumentMatrixProvider
    methods(Static, Access = protected)
        function val = get_cart2beam_to_orient(tm)
            val = tm;
            val = cat(4, val(:,:,:,1:2),...
                    cat(3,...
                    val(:,:,1,3), ...
                    val(:,:,2,4), ...
                    val(:,:,3,3), ...
                    val(:,:,4,4)));
        end 
    end
end